export const Role = {
  PLATFORM_OWNER: "PLATFORM_OWNER",
  PLATFORM_ADMIN: "PLATFORM_ADMIN",
  PLATFORM_OPERATIONS: "PLATFORM_OPERATIONS",
  ORGANIZATION_OWNER: "ORGANIZATION_OWNER",
  HR_OPERATIONS_ADMIN: "HR_OPERATIONS_ADMIN",
  FINANCE_ADMIN: "FINANCE_ADMIN",
  AUDIT_ADMIN: "AUDIT_ADMIN",
  REGIONAL_MANAGER: "REGIONAL_MANAGER",
  CORPORATE_ADMIN: "CORPORATE_ADMIN",
  FINANCE_USER: "FINANCE_USER",
  FINANCE: "FINANCE",
  HR: "HR",
  PROPERTY_MANAGER: "PROPERTY_MANAGER",
  DEPARTMENT_MANAGER: "DEPARTMENT_MANAGER",
  FRONT_DESK: "FRONT_DESK",
  HOUSEKEEPING: "HOUSEKEEPING",
  MAINTENANCE: "MAINTENANCE",
  NIGHT_AUDITOR: "NIGHT_AUDITOR",
  STAFFING_OWNER: "STAFFING_OWNER",
  RECRUITER: "RECRUITER",
  ACCOUNT_MANAGER: "ACCOUNT_MANAGER",
  STAFFING_ADMIN: "STAFFING_ADMIN",
  STAFFING_BILLING: "STAFFING_BILLING",
  EMPLOYEE: "EMPLOYEE",
} as const

export type Role = (typeof Role)[keyof typeof Role]

export const ROLES = Object.values(Role)

export const ROLE_LABELS: Record<Role, string> = {
  [Role.PLATFORM_OWNER]: "Platform Owner",
  [Role.PLATFORM_ADMIN]: "Platform Admin",
  [Role.PLATFORM_OPERATIONS]: "Platform Operations",
  [Role.ORGANIZATION_OWNER]: "Organization Owner",
  [Role.HR_OPERATIONS_ADMIN]: "HR & Operations Admin",
  [Role.FINANCE_ADMIN]: "Finance Admin",
  [Role.AUDIT_ADMIN]: "Audit Admin",
  [Role.REGIONAL_MANAGER]: "Regional Manager",
  [Role.CORPORATE_ADMIN]: "Corporate Admin",
  [Role.FINANCE_USER]: "Finance User",
  [Role.FINANCE]: "Finance",
  [Role.HR]: "HR",
  [Role.PROPERTY_MANAGER]: "Property Manager",
  [Role.DEPARTMENT_MANAGER]: "Department Manager",
  [Role.FRONT_DESK]: "Front Desk",
  [Role.HOUSEKEEPING]: "Housekeeping",
  [Role.MAINTENANCE]: "Maintenance",
  [Role.NIGHT_AUDITOR]: "Night Auditor",
  [Role.STAFFING_OWNER]: "Staffing Owner",
  [Role.RECRUITER]: "Recruiter",
  [Role.ACCOUNT_MANAGER]: "Account Manager",
  [Role.STAFFING_ADMIN]: "Staffing Admin",
  [Role.STAFFING_BILLING]: "Staffing Billing",
  [Role.EMPLOYEE]: "Employee",
}
