ALTER TYPE "AttendanceRecordStatus" ADD VALUE IF NOT EXISTS 'COMPLETED';
ALTER TYPE "AttendanceRecordStatus" ADD VALUE IF NOT EXISTS 'FLAGGED_FOR_MANAGER_REVIEW';

ALTER TYPE "AttendanceExceptionType" ADD VALUE IF NOT EXISTS 'UNSCHEDULED_PROPERTY_CLOCK_IN';
